enum TeaType(val displayName: String, val parent: Option[TeaType] = None):
  case Blend extends TeaType("Blend")
  case ChenPi extends TeaType("Chen Pi", Some(Blend))
  case Rose extends TeaType("Rose", Some(Blend))
  case WhiteTea extends TeaType("White Tea")
  case BaiMuDan extends TeaType("Bai Mu Dan", Some(WhiteTea))
  case ShouMei extends TeaType("Shou Mei", Some(WhiteTea))
  case YellowTea extends TeaType("Yellow Tea")
  case GreenTea extends TeaType("Green Tea")
  case LongJing extends TeaType("Long Jing", Some(GreenTea))
  case BiLuoChun extends TeaType("Bi Luo Chun", Some(GreenTea))
  case MaoFeng extends TeaType("Mao Feng", Some(GreenTea))
  case HouKui extends TeaType("Hou Kui", Some(GreenTea))
  case Sencha extends TeaType("Sencha", Some(GreenTea))
  case Genmaicha extends TeaType("Genmaicha", Some(GreenTea))
  case Oolong extends TeaType("Oolong")
  case YanCha extends TeaType("Yan Cha", Some(Oolong))
  case DanCong extends TeaType("Dan Cong", Some(Oolong))
  case BaoZhong extends TeaType("Bao Zhong", Some(Oolong))
  case DongDing extends TeaType("Dong Ding", Some(Oolong))
  case RedTea extends TeaType("Red Tea")
  case DianHong extends TeaType("Dian Hong", Some(RedTea))
  case DarkTea extends TeaType("Dark Tea")
  case ShengPuerh extends TeaType("Sheng Puerh", Some(DarkTea))
  case ShuPuerh extends TeaType("Shu Puerh", Some(DarkTea))
  case LiuBao extends TeaType("Liu Bao", Some(DarkTea))
  case FuZhuan extends TeaType("Fu Zhuan", Some(DarkTea))
  case LiuAn extends TeaType("Liu An", Some(DarkTea))
  case TianJian extends TeaType("Tian Jian", Some(DarkTea))
  case HuangPian extends TeaType("Huang Pian", Some(DarkTea))
  case Yabao extends TeaType("Yabao")
  case Darjeeling extends TeaType("Darjeeling")
  case PurpleTea extends TeaType("Purple Tea")
