package cz.dusanrychnovsky.myteacollection.scraper.domain

enum TeaType(val parent: Option[TeaType] = None):
  case Blend      extends TeaType()
  case ChenPi     extends TeaType(Some(Blend))
  case Rose       extends TeaType(Some(Blend))
  case WhiteTea   extends TeaType()
  case BaiMuDan   extends TeaType(Some(WhiteTea))
  case ShouMei    extends TeaType(Some(WhiteTea))
  case YellowTea  extends TeaType()
  case GreenTea   extends TeaType()
  case LongJing   extends TeaType(Some(GreenTea))
  case BiLuoChun  extends TeaType(Some(GreenTea))
  case MaoFeng    extends TeaType(Some(GreenTea))
  case HouKui     extends TeaType(Some(GreenTea))
  case Sencha     extends TeaType(Some(GreenTea))
  case Genmaicha  extends TeaType(Some(GreenTea))
  case Oolong     extends TeaType()
  case YanCha     extends TeaType(Some(Oolong))
  case DanCong    extends TeaType(Some(Oolong))
  case BaoZhong   extends TeaType(Some(Oolong))
  case DongDing   extends TeaType(Some(Oolong))
  case RedTea     extends TeaType()
  case DianHong   extends TeaType(Some(RedTea))
  case DarkTea    extends TeaType()
  case ShengPuerh extends TeaType(Some(DarkTea))
  case ShuPuerh   extends TeaType(Some(DarkTea))
  case LiuBao     extends TeaType(Some(DarkTea))
  case FuZhuan    extends TeaType(Some(DarkTea))
  case LiuAn      extends TeaType(Some(DarkTea))
  case TianJian   extends TeaType(Some(DarkTea))
  case HuangPian  extends TeaType(Some(DarkTea))
  case Yabao      extends TeaType()
  case Darjeeling extends TeaType()
  case PurpleTea  extends TeaType()
